spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "chat-message"

chat:
  message:
    secret: "key"

server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    com.chat.message: DEBUG
    org.hibernate: DEBUG
    root: DEBUG
